
[project]
name = 'project6'
description = ''
authors = [saurabhvishwakarma]
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.supply-chain-verification]
path = 'contracts supply-chain-verification.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
